/**
 * Capabilities DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capabilities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Capabilities Domain Module - Composition root
 *
 * DDD: Composition root for capabilities domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CapabilityRepositoryAdapter,
  ForceTagRepositoryAdapter,
  RegionalConstraintRepositoryAdapter,
} from "@alliora/adapters/capabilities";
import { getIdGeneratorService } from "@alliora/adapters";
import type { AdapterDynamoDBClient } from "@alliora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateCapability,
  ExecuteCreateRegionalConstraint,
  ExecuteGetCapability,
  ExecuteListCapabilities,
  ExecuteListRegionalConstraints,
  ExecuteTagCapabilityForces,
  ExecuteUpdateCapability,
} from "@alliora/services/capabilities/usecases";
// Ports (interfaces)
import type {
  CapabilityRepository,
  ForceTagRepository,
  RegionalConstraintRepository,
} from "@alliora/services/capabilities/ports";

export interface CapabilitiesDomainModule {
  repos: {
    capabilities: CapabilityRepository;
    forceTags: ForceTagRepository;
    regionalConstraints: RegionalConstraintRepository;
  };
  useCases: {
    capabilities: {
      create: ExecuteCreateCapability;
      get: ExecuteGetCapability;
      list: ExecuteListCapabilities;
      update: ExecuteUpdateCapability;
    };
    forceTags: {
      get: ExecuteTagCapabilityForces;
    };
    regionalConstraints: {
      create: ExecuteCreateRegionalConstraint;
      list: ExecuteListRegionalConstraints;
    };
  };
}

export function buildCapabilitiesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CapabilitiesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      capabilities?: CapabilityRepository;
      forceTags?: ForceTagRepository;
      regionalConstraints?: RegionalConstraintRepository;
    } = {};

    obj.capabilities = new CapabilityRepositoryAdapter(dynamoClient);
    obj.forceTags = new ForceTagRepositoryAdapter(dynamoClient);
    obj.regionalConstraints = new RegionalConstraintRepositoryAdapter(dynamoClient);
    return {
      capabilities: obj.capabilities!,
      forceTags: obj.forceTags!,
      regionalConstraints: obj.regionalConstraints!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    capabilities: {
      create: new ExecuteCreateCapability(executionContext, idGenerator, repos.capabilities),
      get: new ExecuteGetCapability(executionContext, idGenerator, repos.capabilities),
      list: new ExecuteListCapabilities(executionContext, idGenerator, repos.capabilities),
      update: new ExecuteUpdateCapability(executionContext, idGenerator, repos.capabilities),
    },
    forceTags: {
      get: new ExecuteTagCapabilityForces(executionContext, idGenerator, repos.forceTags),
    },
    regionalConstraints: {
      create: new ExecuteCreateRegionalConstraint(executionContext, idGenerator, repos.regionalConstraints),
      list: new ExecuteListRegionalConstraints(executionContext, idGenerator, repos.regionalConstraints),
    },
  };
  return { repos, useCases: useCases as CapabilitiesDomainModule["useCases"] };
}
