/**
 * ListSitDependencies handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dependencies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listSitDependencies } from "@alliora/api-server/domains/dependencies/handlers";
import type { DependenciesDDDDependencies } from "@alliora/api-server/domains/dependencies";
import { createDependency as createDependencyEntity } from "@alliora/factories/dependencies";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@alliora/tests/shared";
import { DEPENDENCIES_USE_CASES } from "../__factories__/use-cases.js";

describe("ListSitDependencies", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DependenciesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DependenciesDDDDependencies>(
      DEPENDENCIES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createDependencyEntity({ orgId }),
      createDependencyEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListSitDependencies, "execute").mockResolvedValue(useCaseResult);

    await listSitDependencies(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListSitDependencies.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
