/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: stagegates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the stagegates domain.
 * Use these factories in tests to create test data.
 */

export { createEvidence } from "./evidence/entity/evidence.entity.factory.js";
export { createOutcome } from "./outcome/entity/outcome.entity.factory.js";
export { createStageGate } from "./stage-gate/entity/stage-gate.entity.factory.js";
