/**
 * ExecuteCreateCapability - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capabilities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateCapability Use Case
 *
 * DDD: Application use case for create Capability.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateCapabilityInput, CreateCapabilityOutput } from "../dto/capability.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alliora/services/_shared/index.js";
import type { CapabilityRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateCapability {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly capability: CapabilityRepository
  ) {}

  async execute(input: CreateCapabilityInput): Promise<CreateCapabilityOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.capId();

    // All field names extracted from OpenAPI spec: economicOwner, name, sourceType, vendorName
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }
    if (!input.economicOwner) {
      throw new ValidationError("economicOwner is required");
    }
    if (!input.sourceType) {
      throw new ValidationError("sourceType is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (capabilities domain)
    const entityId = this.idGenerator.capId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.capability.createCapability({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateCapabilityOutput;
  }
}
