/**
 * ExecuteListRegionalConstraints - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capabilities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListRegionalConstraints Use Case
 *
 * DDD: Application use case for list RegionalConstraint.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListRegionalConstraintsInput, ListRegionalConstraintsOutput } from "../dto/regional-constraint.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alliora/services/_shared/index.js";
import type { RegionalConstraintRepository } from "../ports";

export class ExecuteListRegionalConstraints {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly regionalConstraint: RegionalConstraintRepository
  ) {}

  async execute(input: ListRegionalConstraintsInput): Promise<ListRegionalConstraintsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.capId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.regionalConstraint.listRegionalConstraints({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListRegionalConstraintsOutput;
  }
}
