/**
 * GetPlatformRiskAlert handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getPlatformRiskAlert } from "@alliora/api-server/domains/alerts/handlers";
import type { AlertsDDDDependencies } from "@alliora/api-server/domains/alerts";
import { createAlert as createAlertEntity } from "@alliora/factories/alerts";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@alliora/tests/shared";
import { ALERTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetPlatformRiskAlert", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AlertsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AlertsDDDDependencies>(
      ALERTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createAlertEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetPlatformRiskAlert, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { alertId: entity.id };

    await getPlatformRiskAlert(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetPlatformRiskAlert.execute).toHaveBeenCalledWith(expect.objectContaining({ alertId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { alertId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetPlatformRiskAlert, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getPlatformRiskAlert(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
