/**
 * RaisePlatformRiskAlert handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { raisePlatformRiskAlert } from "@alliora/api-server/domains/alerts/handlers";
import type { AlertsDDDDependencies } from "@alliora/api-server/domains/alerts";
import { createAlert as createAlertEntity } from "@alliora/factories/alerts";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@alliora/tests/shared";
import { ALERTS_USE_CASES } from "../__factories__/use-cases.js";

describe("RaisePlatformRiskAlert", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AlertsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AlertsDDDDependencies>(
      ALERTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createAlertEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRaisePlatformRiskAlert, "execute").mockResolvedValue(useCaseResult);

    await raisePlatformRiskAlert(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRaisePlatformRiskAlert.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
