/**
 * TagCapabilityForces handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capabilities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { tagCapabilityForces } from "@alliora/api-server/domains/capabilities/handlers";
import type { CapabilitiesDDDDependencies } from "@alliora/api-server/domains/capabilities";
import { createForceTag as createForceTagEntity } from "@alliora/factories/capabilities";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@alliora/tests/shared";
import { CAPABILITIES_USE_CASES } from "../__factories__/use-cases.js";

describe("TagCapabilityForces", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: CapabilitiesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<CapabilitiesDDDDependencies>(
      CAPABILITIES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createForceTagEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeTagCapabilityForces, "execute").mockResolvedValue(useCaseResult);

    await tagCapabilityForces(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeTagCapabilityForces.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
