/**
 * Capability Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capabilities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { CapabilityEntity } from "@alliora/core/capabilities/models/index.js";
import { capabilitiesSchemas } from "@alliora/core/capabilities";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cap";

export function createCapability(overrides: Partial<CapabilityEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    capabilityId: overrides.capabilityId ?? `cap_${ulid().toLowerCase()}`,
    economicOwner: overrides.economicOwner ?? faker.lorem.word(),
    name: overrides.name ?? faker.person.fullName(),
    sourceType: overrides.sourceType ?? "fintech",
    status: overrides.status ?? "intake",
    ...overrides,
  };

  return capabilitiesSchemas.Capability.parse(raw);
}

export function capabilityBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createCapability(overrides));
}
