/**
 * CapabilityRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capabilities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CapabilityRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CapabilityRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CapabilityRepository,
} from "@alliora/services/capabilities";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CapabilityRepositoryDdb } from "./capability-repository.ddb.js";

/**
 * CapabilityRepositoryAdapter
 *
 * Implements CapabilityRepository port for infrastructure layer.
 */
export class CapabilityRepositoryAdapter implements CapabilityRepository {
  private readonly ddb: CapabilityRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CapabilityRepositoryDdb(this.dynamoClient);
  }

  async listCapabilities(input: Parameters<CapabilityRepository['listCapabilities']>[0]): Promise<Awaited<ReturnType<CapabilityRepository['listCapabilities']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listCapabilities(input);
  }

  async createCapability(input: Parameters<CapabilityRepository['createCapability']>[0]): Promise<Awaited<ReturnType<CapabilityRepository['createCapability']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createCapability(input);
  }

  async getCapability(input: Parameters<CapabilityRepository['getCapability']>[0]): Promise<Awaited<ReturnType<CapabilityRepository['getCapability']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getCapability(input);
  }

  async updateCapability(input: Parameters<CapabilityRepository['updateCapability']>[0]): Promise<Awaited<ReturnType<CapabilityRepository['updateCapability']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateCapability(input);
  }
}
