/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capabilities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./capability-repository.ddb.js";
export * from "./force-tag-repository.ddb.js";
export * from "./regional-constraint-repository.ddb.js";
export * from "./capability-repository.adapter.js";
export * from "./force-tag-repository.adapter.js";
export * from "./regional-constraint-repository.adapter.js";
