/**
 * ExecuteGetBionicRoleMap - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: workforce
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetBionicRoleMap Use Case
 *
 * DDD: Application use case for get WorkforceMap.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetBionicRoleMapInput, GetBionicRoleMapOutput } from "../dto/workforce-map.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alliora/services/_shared/index.js";
import type { WorkforceMapRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetBionicRoleMap {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly workforceMap: WorkforceMapRepository
  ) {}

  async execute(input: GetBionicRoleMapInput): Promise<GetBionicRoleMapOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.bioId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).mapId) {
      throw new ValidationError("mapId is required");
    }
    const mapId = (input as any).mapId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.workforceMap.getBionicRoleMap({ mapId: mapId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${mapId}`);
    }

    return entity as GetBionicRoleMapOutput;
  }
}
