/**
 * ExecuteSignBionicRoleMap - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: workforce
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSignBionicRoleMap Use Case
 *
 * DDD: Application use case for get HrSignoff.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SignBionicRoleMapInput, SignBionicRoleMapOutput } from "../dto/hr-signoff.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alliora/services/_shared/index.js";
import type { HrSignoffRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteSignBionicRoleMap {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly hrSignoff: HrSignoffRepository
  ) {}

  async execute(input: SignBionicRoleMapInput): Promise<SignBionicRoleMapOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.bioId();

    // All field names extracted from OpenAPI spec: conductSigned, hrSigned
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).mapId) {
      throw new ValidationError("mapId is required");
    }
    const mapId = (input as any).mapId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.hrSignoff.signBionicRoleMap({ ...input, mapId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${mapId}`);
    }

    return entity as SignBionicRoleMapOutput;
  }
}
