/**
 * ExecuteCreateStageGate - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: stagegates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateStageGate Use Case
 *
 * DDD: Application use case for create StageGate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateStageGateInput, CreateStageGateOutput } from "../dto/stage-gate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alliora/services/_shared/index.js";
import type { StageGateRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateStageGate {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly stageGate: StageGateRepository
  ) {}

  async execute(input: CreateStageGateInput): Promise<CreateStageGateOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.gatId();

    // All field names extracted from OpenAPI spec: capabilityId, dayMarker
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.capabilityId) {
      throw new ValidationError("capabilityId is required");
    }
    if (!input.dayMarker) {
      throw new ValidationError("dayMarker is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (stagegates domain)
    const entityId = this.idGenerator.gatId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.stageGate.createStageGate({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateStageGateOutput;
  }
}
