/**
 * ExecuteGetEvidencePack - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: stagegates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetEvidencePack Use Case
 *
 * DDD: Application use case for get Evidence.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetEvidencePackInput, GetEvidencePackOutput } from "../dto/evidence.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alliora/services/_shared/index.js";
import type { EvidenceRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetEvidencePack {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly evidence: EvidenceRepository
  ) {}

  async execute(input: GetEvidencePackInput): Promise<GetEvidencePackOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.gatId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).gateId) {
      throw new ValidationError("gateId is required");
    }
    const gateId = (input as any).gateId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.evidence.getEvidencePack({ gateId: gateId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${gateId}`);
    }

    return entity as GetEvidencePackOutput;
  }
}
