/**
 * ExperienceMapRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExperienceMapRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ExperienceMapRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ExperienceMapRepository,
} from "@alliora/services/experience";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ExperienceMapRepositoryDdb } from "./experience-map-repository.ddb.js";

/**
 * ExperienceMapRepositoryAdapter
 *
 * Implements ExperienceMapRepository port for infrastructure layer.
 */
export class ExperienceMapRepositoryAdapter implements ExperienceMapRepository {
  private readonly ddb: ExperienceMapRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ExperienceMapRepositoryDdb(this.dynamoClient);
  }

  async listExperienceOwnershipMaps(input: Parameters<ExperienceMapRepository['listExperienceOwnershipMaps']>[0]): Promise<Awaited<ReturnType<ExperienceMapRepository['listExperienceOwnershipMaps']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listExperienceOwnershipMaps(input);
  }

  async createExperienceOwnershipMap(input: Parameters<ExperienceMapRepository['createExperienceOwnershipMap']>[0]): Promise<Awaited<ReturnType<ExperienceMapRepository['createExperienceOwnershipMap']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createExperienceOwnershipMap(input);
  }

  async getExperienceOwnershipMap(input: Parameters<ExperienceMapRepository['getExperienceOwnershipMap']>[0]): Promise<Awaited<ReturnType<ExperienceMapRepository['getExperienceOwnershipMap']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getExperienceOwnershipMap(input);
  }
}
