/**
 * HrSignoff DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: workforce
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HrSignoff DTOs
 *
 * DDD: Application DTOs for HrSignoff use cases.
 */

import type { SignBionicRoleMapParams, SignBionicRoleMapRequestInput } from "@alliora/core/workforce/types";

export type SignBionicRoleMapInput = SignBionicRoleMapParams & SignBionicRoleMapRequestInput;

export type SignBionicRoleMapOutput = {};
