/**
 * WorkforceMap DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: workforce
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * WorkforceMap DTOs
 *
 * DDD: Application DTOs for WorkforceMap use cases.
 */

import type { CreateBionicRoleMapRequestInput, GetBionicRoleMapParams, ListBionicRoleMapsParams } from "@alliora/core/workforce/types";

export type ListBionicRoleMapsInput = ListBionicRoleMapsParams;

export type CreateBionicRoleMapInput = CreateBionicRoleMapRequestInput;

export type GetBionicRoleMapInput = GetBionicRoleMapParams;

export type ListBionicRoleMapsOutput = {};

export type CreateBionicRoleMapOutput = {};

export type GetBionicRoleMapOutput = {};
