/**
 * Reports DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Reports Domain Module - Composition root
 *
 * DDD: Composition root for reports domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  PortfolioRepositoryAdapter,
  ReportRepositoryAdapter,
  PublishPublisherAdapter,
} from "@alliora/adapters/reports";
import { getIdGeneratorService } from "@alliora/adapters";
import type { AdapterDynamoDBClient } from "@alliora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGeneratePortfolioReport,
  ExecuteGetPortfolioReport,
  ExecuteListPortfolioReports,
  ExecutePublishPortfolioReport,
} from "@alliora/services/reports/usecases";
// Ports (interfaces)
import type {
  PortfolioRepository,
  ReportRepository,
  PublishPublisher,
} from "@alliora/services/reports/ports";

export interface ReportsDomainModule {
  repos: {
    portfolios: PortfolioRepository;
    reports: ReportRepository;
    publishes: PublishPublisher;
  };
  useCases: {
    portfolios: {
      get: ExecuteGetPortfolioReport;
    };
    reports: {
      get: ExecuteGeneratePortfolioReport;
      list: ExecuteListPortfolioReports;
    };
    publishes: {
      get: ExecutePublishPortfolioReport;
    };
  };
}

export function buildReportsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ReportsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      portfolios?: PortfolioRepository;
      reports?: ReportRepository;
      publishes?: PublishPublisher;
    } = {};

    obj.portfolios = new PortfolioRepositoryAdapter(dynamoClient);
    obj.reports = new ReportRepositoryAdapter(dynamoClient);
    obj.publishes = new PublishPublisherAdapter();
    return {
      portfolios: obj.portfolios!,
      reports: obj.reports!,
      publishes: obj.publishes!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    portfolios: {
      get: new ExecuteGetPortfolioReport(executionContext, idGenerator, repos.portfolios),
    },
    reports: {
      get: new ExecuteGeneratePortfolioReport(executionContext, idGenerator, repos.reports),
      list: new ExecuteListPortfolioReports(executionContext, idGenerator, repos.reports),
    },
    publishes: {
      get: new ExecutePublishPortfolioReport(executionContext, idGenerator, repos.publishes, repos.reports),
    },
  };
  return { repos, useCases: useCases as ReportsDomainModule["useCases"] };
}
