/**
 * Experience DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Experience Domain Module - Composition root
 *
 * DDD: Composition root for experience domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ExperienceMapRepositoryAdapter,
  LiabilityRepositoryAdapter,
  SignRepositoryAdapter,
} from "@alliora/adapters/experience";
import { getIdGeneratorService } from "@alliora/adapters";
import type { AdapterDynamoDBClient } from "@alliora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAttachLiabilityTerms,
  ExecuteCreateExperienceOwnershipMap,
  ExecuteGetExperienceOwnershipMap,
  ExecuteListExperienceOwnershipMaps,
  ExecuteSignLiabilityTerms,
} from "@alliora/services/experience/usecases";
// Ports (interfaces)
import type {
  ExperienceMapRepository,
  LiabilityRepository,
  SignRepository,
} from "@alliora/services/experience/ports";

export interface ExperienceDomainModule {
  repos: {
    liabilities: LiabilityRepository;
    maps: ExperienceMapRepository;
    signs: SignRepository;
  };
  useCases: {
    liabilities: {
      get: ExecuteAttachLiabilityTerms;
    };
    maps: {
      create: ExecuteCreateExperienceOwnershipMap;
      get: ExecuteGetExperienceOwnershipMap;
      list: ExecuteListExperienceOwnershipMaps;
    };
    signs: {
      get: ExecuteSignLiabilityTerms;
    };
  };
}

export function buildExperienceDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ExperienceDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      liabilities?: LiabilityRepository;
      maps?: ExperienceMapRepository;
      signs?: SignRepository;
    } = {};

    obj.liabilities = new LiabilityRepositoryAdapter(dynamoClient);
    obj.maps = new ExperienceMapRepositoryAdapter(dynamoClient);
    obj.signs = new SignRepositoryAdapter(dynamoClient);
    return {
      liabilities: obj.liabilities!,
      maps: obj.maps!,
      signs: obj.signs!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    liabilities: {
      get: new ExecuteAttachLiabilityTerms(executionContext, idGenerator, repos.liabilities),
    },
    maps: {
      create: new ExecuteCreateExperienceOwnershipMap(executionContext, idGenerator, repos.maps),
      get: new ExecuteGetExperienceOwnershipMap(executionContext, idGenerator, repos.maps),
      list: new ExecuteListExperienceOwnershipMaps(executionContext, idGenerator, repos.maps),
    },
    signs: {
      get: new ExecuteSignLiabilityTerms(executionContext, idGenerator, repos.signs),
    },
  };
  return { repos, useCases: useCases as ExperienceDomainModule["useCases"] };
}
