/**
 * Dependencies Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dependencies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const registerSitDependency_Body = z
  .object({
    vendorName: z.string(),
    capabilityArea: z.enum([
      'cloud',
      'data',
      'model',
      'payments',
      'kyc',
      'other',
    ]),
    concentrationScore: z.number(),
    concentrationLimit: z.number().optional(),
    exitPlanPresent: z.boolean(),
    exitPlanSummary: z.string().optional(),
    boardVisible: z.boolean().optional(),
  })
  .passthrough();
const updateSitDependency_Body = z
  .object({
    concentrationScore: z.number(),
    exitPlanPresent: z.boolean(),
    exitPlanSummary: z.string(),
    boardVisible: z.boolean(),
  })
  .partial()
  .passthrough();
const requestSitLimitException_Body = z
  .object({
    dependencyId: z.string().regex(/^sit_[0-9A-HJKMNP-TV-Z]{26}$/),
    rationale: z.string(),
  })
  .passthrough();

export const schemas: any = {
  registerSitDependency_Body,
  updateSitDependency_Body,
  requestSitLimitException_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/dependencies',
    alias: 'listSitDependencies',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(100).optional().default(25),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  dependencyId: z
                    .string()
                    .regex(/^sit_[0-9A-HJKMNP-TV-Z]{26}$/),
                  vendorName: z.string(),
                  capabilityArea: z.enum([
                    'cloud',
                    'data',
                    'model',
                    'payments',
                    'kyc',
                    'other',
                  ]),
                  concentrationScore: z.number(),
                  concentrationLimit: z.number().optional(),
                  exitPlanPresent: z.boolean(),
                  exitPlanSummary: z.string().optional(),
                  boardVisible: z.boolean().optional(),
                  spendBlocked: z.boolean(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }).optional(),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/dependencies',
    alias: 'registerSitDependency',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: registerSitDependency_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            dependencyId: z.string().regex(/^sit_[0-9A-HJKMNP-TV-Z]{26}$/),
            vendorName: z.string(),
            capabilityArea: z.enum([
              'cloud',
              'data',
              'model',
              'payments',
              'kyc',
              'other',
            ]),
            concentrationScore: z.number(),
            concentrationLimit: z.number().optional(),
            exitPlanPresent: z.boolean(),
            exitPlanSummary: z.string().optional(),
            boardVisible: z.boolean().optional(),
            spendBlocked: z.boolean(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 422,
        description: `Semantically invalid request (e.g. PACK_EMPTY)`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/dependencies/:dependencyId',
    alias: 'getSitDependency',
    requestFormat: 'json',
    parameters: [
      {
        name: 'dependencyId',
        type: 'Path',
        schema: z.string().regex(/^sit_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            dependencyId: z.string().regex(/^sit_[0-9A-HJKMNP-TV-Z]{26}$/),
            vendorName: z.string(),
            capabilityArea: z.enum([
              'cloud',
              'data',
              'model',
              'payments',
              'kyc',
              'other',
            ]),
            concentrationScore: z.number(),
            concentrationLimit: z.number().optional(),
            exitPlanPresent: z.boolean(),
            exitPlanSummary: z.string().optional(),
            boardVisible: z.boolean().optional(),
            spendBlocked: z.boolean(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'patch',
    path: '/v1/dependencies/:dependencyId',
    alias: 'updateSitDependency',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: updateSitDependency_Body,
      },
      {
        name: 'dependencyId',
        type: 'Path',
        schema: z.string().regex(/^sit_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            dependencyId: z.string().regex(/^sit_[0-9A-HJKMNP-TV-Z]{26}$/),
            vendorName: z.string(),
            capabilityArea: z.enum([
              'cloud',
              'data',
              'model',
              'payments',
              'kyc',
              'other',
            ]),
            concentrationScore: z.number(),
            concentrationLimit: z.number().optional(),
            exitPlanPresent: z.boolean(),
            exitPlanSummary: z.string().optional(),
            boardVisible: z.boolean().optional(),
            spendBlocked: z.boolean(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/dependencies/:dependencyId/spend-block',
    alias: 'getSitSpendBlock',
    requestFormat: 'json',
    parameters: [
      {
        name: 'dependencyId',
        type: 'Path',
        schema: z.string().regex(/^sit_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            dependencyId: z.string().regex(/^sit_[0-9A-HJKMNP-TV-Z]{26}$/),
            spendBlocked: z.boolean(),
            reasons: z.array(z.string()),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/sit-exceptions',
    alias: 'listSitLimitExceptions',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(100).optional().default(25),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  exceptionId: z.string().regex(/^lim_[0-9A-HJKMNP-TV-Z]{26}$/),
                  dependencyId: z
                    .string()
                    .regex(/^sit_[0-9A-HJKMNP-TV-Z]{26}$/),
                  status: z.enum(['requested', 'approved', 'denied']),
                  rationale: z.string(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }).optional(),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/sit-exceptions',
    alias: 'requestSitLimitException',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: requestSitLimitException_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            exceptionId: z.string().regex(/^lim_[0-9A-HJKMNP-TV-Z]{26}$/),
            dependencyId: z.string().regex(/^sit_[0-9A-HJKMNP-TV-Z]{26}$/),
            status: z.enum(['requested', 'approved', 'denied']),
            rationale: z.string(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 422,
        description: `Semantically invalid request (e.g. PACK_EMPTY)`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
