/**
 * ExecuteAcknowledgePlatformRiskAlert - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteAcknowledgePlatformRiskAlert Use Case
 *
 * DDD: Application use case for get Acknowledge.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { AcknowledgePlatformRiskAlertInput, AcknowledgePlatformRiskAlertOutput } from "../dto/acknowledge.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alliora/services/_shared/index.js";
import type { AcknowledgeRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteAcknowledgePlatformRiskAlert {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly acknowledge: AcknowledgeRepository
  ) {}

  async execute(input: AcknowledgePlatformRiskAlertInput): Promise<AcknowledgePlatformRiskAlertOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.altId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).alertId) {
      throw new ValidationError("alertId is required");
    }
    const alertId = (input as any).alertId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.acknowledge.acknowledgePlatformRiskAlert({ alertId: alertId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${alertId}`);
    }

    return entity as AcknowledgePlatformRiskAlertOutput;
  }
}
