/**
 * Test Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/decisions.openapi.types.js";
import { schemas } from "../schemas/decisions.schemas.js";

/**
 * Entity: TestEntity
 * Description: Represents the Test domain model.
 * Source: schemas.ProfitPoolHypothesis
 * Type: Persisted Entity (x-dynamodb)
 */
export const TestEntitySchema = schemas.ProfitPoolHypothesis;
export type TestEntity = components["schemas"]["ProfitPoolHypothesis"];
