/**
 * Evidence DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: stagegates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Evidence DTOs
 *
 * DDD: Application DTOs for Evidence use cases.
 */

import type { GetEvidencePackParams, SubmitEvidencePackParams, SubmitEvidencePackRequestInput } from "@alliora/core/stagegates/types";

export type GetEvidencePackInput = GetEvidencePackParams;

export type SubmitEvidencePackInput = SubmitEvidencePackParams & SubmitEvidencePackRequestInput;

export type GetEvidencePackOutput = {};

export type SubmitEvidencePackOutput = {};
