/**
 * Outcome DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: stagegates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Outcome DTOs
 *
 * DDD: Application DTOs for Outcome use cases.
 */

import type { DecideStageGateOutcomeParams, DecideStageGateOutcomeRequestInput } from "@alliora/core/stagegates/types";

export type DecideStageGateOutcomeInput = DecideStageGateOutcomeParams & DecideStageGateOutcomeRequestInput;

export type DecideStageGateOutcomeOutput = {};
