/**
 * Report DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Report DTOs
 *
 * DDD: Application DTOs for Report use cases.
 */

import type { GeneratePortfolioReportRequestInput, ListPortfolioReportsParams } from "@alliora/core/reports/types";

export type ListPortfolioReportsInput = ListPortfolioReportsParams;

export type GeneratePortfolioReportInput = GeneratePortfolioReportRequestInput;

export type ListPortfolioReportsOutput = {};

export type GeneratePortfolioReportOutput = {};
