/**
 * ExperienceMap DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExperienceMap DTOs
 *
 * DDD: Application DTOs for ExperienceMap use cases.
 */

import type { CreateExperienceOwnershipMapRequestInput, GetExperienceOwnershipMapParams, ListExperienceOwnershipMapsParams } from "@alliora/core/experience/types";

export type ListExperienceOwnershipMapsInput = ListExperienceOwnershipMapsParams;

export type CreateExperienceOwnershipMapInput = CreateExperienceOwnershipMapRequestInput;

export type GetExperienceOwnershipMapInput = GetExperienceOwnershipMapParams;

export type ListExperienceOwnershipMapsOutput = {};

export type CreateExperienceOwnershipMapOutput = {};

export type GetExperienceOwnershipMapOutput = {};
