/**
 * ExecutePublishPortfolioReport - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecutePublishPortfolioReport Use Case
 *
 * DDD: Application use case for get Publish.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { PublishPortfolioReportInput, PublishPortfolioReportOutput } from "../dto/publish.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alliora/services/_shared/index.js";
import type { PublishPublisher, ReportRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecutePublishPortfolioReport {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly publish: PublishPublisher,
    private readonly report: ReportRepository
  ) {}

  async execute(input: PublishPortfolioReportInput): Promise<PublishPortfolioReportOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rptId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).reportId) {
      throw new ValidationError("reportId is required");
    }
    const reportId = (input as any).reportId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.report.publishPortfolioReport({ reportId: reportId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${reportId}`);
    }

    return entity as PublishPortfolioReportOutput;
  }
}
