/**
 * ExecuteListPortfolioReports - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListPortfolioReports Use Case
 *
 * DDD: Application use case for list Report.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListPortfolioReportsInput, ListPortfolioReportsOutput } from "../dto/report.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alliora/services/_shared/index.js";
import type { ReportRepository } from "../ports";

export class ExecuteListPortfolioReports {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly report: ReportRepository
  ) {}

  async execute(input: ListPortfolioReportsInput): Promise<ListPortfolioReportsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rptId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.report.listPortfolioReports({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListPortfolioReportsOutput;
  }
}
