/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as alertsRoutes from "../../domains/alerts/routes/index.js";
import * as capabilitiesRoutes from "../../domains/capabilities/routes/index.js";
import * as decisionsRoutes from "../../domains/decisions/routes/index.js";
import * as dependenciesRoutes from "../../domains/dependencies/routes/index.js";
import * as experienceRoutes from "../../domains/experience/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as reportsRoutes from "../../domains/reports/routes/index.js";
import * as stagegatesRoutes from "../../domains/stagegates/routes/index.js";
import * as workforceRoutes from "../../domains/workforce/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "alerts", mod: alertsRoutes },
  { domain: "capabilities", mod: capabilitiesRoutes },
  { domain: "decisions", mod: decisionsRoutes },
  { domain: "dependencies", mod: dependenciesRoutes },
  { domain: "experience", mod: experienceRoutes },
  {
    domain: "identity", mod: identityRoutes,
    // Keep login/me/logout/refresh registered (API-key + password sessions).
    exclude: ["authRoutes", "signupRoutes", "sessionRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "reports", mod: reportsRoutes },
  { domain: "stagegates", mod: stagegatesRoutes },
  { domain: "workforce", mod: workforceRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
