/**
 * Repository interface for SitException
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: dependencies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  SitExceptionEntity
} from "../models/sit-exception.entity.js";
import type {
  ListSitLimitExceptionsParams,
  SitLimitException
} from "../types/index.js";
/**
 * SitExceptionRepository Interface
 */
export interface SitExceptionRepository extends CreateReadRepository<SitExceptionEntity, SitLimitException, string, ListSitLimitExceptionsParams> {

}
