/**
 * RegionalConstraint Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capabilities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { RegionalConstraintEntity } from "@alliora/core/capabilities/models/index.js";
import { capabilitiesSchemas } from "@alliora/core/capabilities";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cap";

export function createRegionalConstraint(overrides: Partial<RegionalConstraintEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    capabilityId: overrides.capabilityId ?? `cap_${ulid().toLowerCase()}`,
    constraintType: overrides.constraintType ?? "licence",
    region: overrides.region ?? faker.lorem.word(),
    regionalConstraintId: overrides.regionalConstraintId ?? `rgn_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return capabilitiesSchemas.RegionalConstraint.parse(raw);
}

export function regionalConstraintBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createRegionalConstraint(overrides));
}
