/**
 * ListPartnershipContract DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListPartnershipContractsParams } from "@alliora/core/decisions";

export function createListPartnershipContractRequest(overrides: Partial<ListPartnershipContractsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
