/**
 * Repository interface for Escalate
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  EscalateEntity
} from "../models/escalate.entity.js";
import type {
  PlatformRiskAlert
} from "../types/index.js";
/**
 * EscalateRepository Interface
 */
export interface EscalateRepository extends CreateReadRepository<EscalateEntity, PlatformRiskAlert, string, Record<string, never>> {

}
