/**
 * CapabilityRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capabilities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CapabilityRepository Port
 *
 * DDD: Application port for capabilityrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateCapabilityInput, CreateCapabilityOutput, GetCapabilityInput, GetCapabilityOutput, ListCapabilitiesInput, ListCapabilitiesOutput, UpdateCapabilityInput, UpdateCapabilityOutput } from "../dto/capability.dto";
export interface CapabilityRepository {
  listCapabilities(input: ListCapabilitiesInput): Promise<ListCapabilitiesOutput>;
  createCapability(input: CreateCapabilityInput): Promise<CreateCapabilityOutput>;
  getCapability(input: GetCapabilityInput): Promise<GetCapabilityOutput>;
  updateCapability(input: UpdateCapabilityInput): Promise<UpdateCapabilityOutput>;
}

export type { CreateCapabilityInput, CreateCapabilityOutput, GetCapabilityInput, GetCapabilityOutput, ListCapabilitiesInput, ListCapabilitiesOutput, UpdateCapabilityInput, UpdateCapabilityOutput } from "../dto/capability.dto";
