/**
 * ForceTagRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capabilities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ForceTagRepository Port
 *
 * DDD: Application port for forcetagrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { TagCapabilityForcesInput, TagCapabilityForcesOutput } from "../dto/force-tag.dto";
export interface ForceTagRepository {
  tagCapabilityForces(input: TagCapabilityForcesInput): Promise<TagCapabilityForcesOutput>;
}

export type { TagCapabilityForcesInput, TagCapabilityForcesOutput } from "../dto/force-tag.dto";
