/**
 * RegionalConstraintRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capabilities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RegionalConstraintRepository Port
 *
 * DDD: Application port for regionalconstraintrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateRegionalConstraintInput, CreateRegionalConstraintOutput, ListRegionalConstraintsInput, ListRegionalConstraintsOutput } from "../dto/regional-constraint.dto";
export interface RegionalConstraintRepository {
  listRegionalConstraints(input: ListRegionalConstraintsInput): Promise<ListRegionalConstraintsOutput>;
  createRegionalConstraint(input: CreateRegionalConstraintInput): Promise<CreateRegionalConstraintOutput>;
}

export type { CreateRegionalConstraintInput, CreateRegionalConstraintOutput, ListRegionalConstraintsInput, ListRegionalConstraintsOutput } from "../dto/regional-constraint.dto";
