/**
 * ForceTag DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capabilities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ForceTag DTOs
 *
 * DDD: Application DTOs for ForceTag use cases.
 */

import type { TagCapabilityForcesParams, TagCapabilityForcesRequestInput } from "@alliora/core/capabilities/types";

export type TagCapabilityForcesInput = TagCapabilityForcesParams & TagCapabilityForcesRequestInput;

export type TagCapabilityForcesOutput = {};
