/**
 * RegionalConstraint DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capabilities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RegionalConstraint DTOs
 *
 * DDD: Application DTOs for RegionalConstraint use cases.
 */

import type { CreateRegionalConstraintRequestInput, ListRegionalConstraintsParams } from "@alliora/core/capabilities/types";

export type ListRegionalConstraintsInput = ListRegionalConstraintsParams;

export type CreateRegionalConstraintInput = CreateRegionalConstraintRequestInput;

export type ListRegionalConstraintsOutput = {};

export type CreateRegionalConstraintOutput = {};
