/**
 * Handlers for HrSignoff
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: workforce
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { WorkforceDomainModule } from "../dependencies/workforce-ddd.dependencies.js";
import type { SignBionicRoleMapInput } from "@alliora/services/workforce";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/workforce-maps/{mapId}/hr-signoff
 * Operation: signBionicRoleMap
 */
export async function signBionicRoleMap(
  request: FastifyRequest<{ Params: { mapId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: WorkforceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    mapId: request.params.mapId,
    ...((request.body ?? {}) as object),
  };
  const result = await deps.useCases.hrSignoffs.get.execute(input as any);
  return reply.code(200).send(result);
}


