/**
 * Handlers index
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: workforce
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./hr-signoff.handlers.js";
export * from "./workforce-map.handlers.js";
