/**
 * DependencyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dependencies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DependencyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DependencyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DependencyRepository,
} from "@alliora/services/dependencies";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DependencyRepositoryDdb } from "./dependency-repository.ddb.js";

/**
 * DependencyRepositoryAdapter
 *
 * Implements DependencyRepository port for infrastructure layer.
 */
export class DependencyRepositoryAdapter implements DependencyRepository {
  private readonly ddb: DependencyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DependencyRepositoryDdb(this.dynamoClient);
  }

  async listSitDependencies(input: Parameters<DependencyRepository['listSitDependencies']>[0]): Promise<Awaited<ReturnType<DependencyRepository['listSitDependencies']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listSitDependencies(input);
  }

  async registerSitDependency(input: Parameters<DependencyRepository['registerSitDependency']>[0]): Promise<Awaited<ReturnType<DependencyRepository['registerSitDependency']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.registerSitDependency(input);
  }

  async getSitDependency(input: Parameters<DependencyRepository['getSitDependency']>[0]): Promise<Awaited<ReturnType<DependencyRepository['getSitDependency']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getSitDependency(input);
  }

  async updateSitDependency(input: Parameters<DependencyRepository['updateSitDependency']>[0]): Promise<Awaited<ReturnType<DependencyRepository['updateSitDependency']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateSitDependency(input);
  }
}
