/**
 * SitExceptionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dependencies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SitExceptionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SitExceptionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SitExceptionRepository,
} from "@alliora/services/dependencies";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SitExceptionRepositoryDdb } from "./sit-exception-repository.ddb.js";

/**
 * SitExceptionRepositoryAdapter
 *
 * Implements SitExceptionRepository port for infrastructure layer.
 */
export class SitExceptionRepositoryAdapter implements SitExceptionRepository {
  private readonly ddb: SitExceptionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SitExceptionRepositoryDdb(this.dynamoClient);
  }

  async listSitLimitExceptions(input: Parameters<SitExceptionRepository['listSitLimitExceptions']>[0]): Promise<Awaited<ReturnType<SitExceptionRepository['listSitLimitExceptions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listSitLimitExceptions(input);
  }

  async requestSitLimitException(input: Parameters<SitExceptionRepository['requestSitLimitException']>[0]): Promise<Awaited<ReturnType<SitExceptionRepository['requestSitLimitException']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.requestSitLimitException(input);
  }
}
