/**
 * CostCompareRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CostCompareRepository Port
 *
 * DDD: Application port for costcomparerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateCostCompareInput, CreateCostCompareOutput, ListCostComparesInput, ListCostComparesOutput } from "../dto/cost-compare.dto";
export interface CostCompareRepository {
  listCostCompares(input: ListCostComparesInput): Promise<ListCostComparesOutput>;
  createCostCompare(input: CreateCostCompareInput): Promise<CreateCostCompareOutput>;
}

export type { CreateCostCompareInput, CreateCostCompareOutput, ListCostComparesInput, ListCostComparesOutput } from "../dto/cost-compare.dto";
