/**
 * DecisionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DecisionRepository Port
 *
 * DDD: Application port for decisionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetDecisionClassInput, GetDecisionClassOutput, ListDecisionClassesInput, ListDecisionClassesOutput, RecordDecisionClassInput, RecordDecisionClassOutput } from "../dto/decision.dto";
export interface DecisionRepository {
  listDecisionClasses(input: ListDecisionClassesInput): Promise<ListDecisionClassesOutput>;
  recordDecisionClass(input: RecordDecisionClassInput): Promise<RecordDecisionClassOutput>;
  getDecisionClass(input: GetDecisionClassInput): Promise<GetDecisionClassOutput>;
}

export type { GetDecisionClassInput, GetDecisionClassOutput, ListDecisionClassesInput, ListDecisionClassesOutput, RecordDecisionClassInput, RecordDecisionClassOutput } from "../dto/decision.dto";
