/**
 * DecideStageGateOutcome handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: stagegates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { decideStageGateOutcome } from "@alliora/api-server/domains/stagegates/handlers";
import type { StagegatesDDDDependencies } from "@alliora/api-server/domains/stagegates";
import { createOutcome as createOutcomeEntity } from "@alliora/factories/stagegates";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@alliora/tests/shared";
import { STAGEGATES_USE_CASES } from "../__factories__/use-cases.js";

describe("DecideStageGateOutcome", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: StagegatesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<StagegatesDDDDependencies>(
      STAGEGATES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createOutcomeEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeDecideStageGateOutcome, "execute").mockResolvedValue(useCaseResult);

    await decideStageGateOutcome(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeDecideStageGateOutcome.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
