/**
 * Evidence Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: stagegates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/stagegates.openapi.types.js";
import { schemas } from "../schemas/stagegates.schemas.js";

/**
 * Entity: EvidenceEntity
 * Description: Represents the Evidence domain model.
 * Source: schemas.EvidencePack
 * Type: Persisted Entity (x-dynamodb)
 */
export const EvidenceEntitySchema = schemas.EvidencePack;
export type EvidenceEntity = components["schemas"]["EvidencePack"];
