/**
 * ExecuteCreatePartnershipContract - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreatePartnershipContract Use Case
 *
 * DDD: Application use case for create PartnershipContract.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreatePartnershipContractInput, CreatePartnershipContractOutput } from "../dto/partnership-contract.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alliora/services/_shared/index.js";
import type { PartnershipContractRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreatePartnershipContract {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly partnershipContract: PartnershipContractRepository
  ) {}

  async execute(input: CreatePartnershipContractInput): Promise<CreatePartnershipContractOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dcsId();

    // All field names extracted from OpenAPI spec: capabilityId, experienceMapId, status
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.capabilityId) {
      throw new ValidationError("capabilityId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (decisions domain)
    const entityId = this.idGenerator.dcsId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.partnershipContract.createPartnershipContract({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreatePartnershipContractOutput;
  }
}
