/**
 * ExecuteListCostCompares - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListCostCompares Use Case
 *
 * DDD: Application use case for list CostCompare.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListCostComparesInput, ListCostComparesOutput } from "../dto/cost-compare.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alliora/services/_shared/index.js";
import type { CostCompareRepository } from "../ports";

export class ExecuteListCostCompares {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly costCompare: CostCompareRepository
  ) {}

  async execute(input: ListCostComparesInput): Promise<ListCostComparesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dcsId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.costCompare.listCostCompares({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListCostComparesOutput;
  }
}
