/**
 * ExecuteListPartnershipContracts - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListPartnershipContracts Use Case
 *
 * DDD: Application use case for list PartnershipContract.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListPartnershipContractsInput, ListPartnershipContractsOutput } from "../dto/partnership-contract.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alliora/services/_shared/index.js";
import type { PartnershipContractRepository } from "../ports";

export class ExecuteListPartnershipContracts {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly partnershipContract: PartnershipContractRepository
  ) {}

  async execute(input: ListPartnershipContractsInput): Promise<ListPartnershipContractsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dcsId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.partnershipContract.listPartnershipContracts({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListPartnershipContractsOutput;
  }
}
