/**
 * GetDecisionClass handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getDecisionClass } from "@alliora/api-server/domains/decisions/handlers";
import type { DecisionsDDDDependencies } from "@alliora/api-server/domains/decisions";
import { createDecision as createDecisionEntity } from "@alliora/factories/decisions";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@alliora/tests/shared";
import { DECISIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetDecisionClass", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DecisionsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DecisionsDDDDependencies>(
      DECISIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createDecisionEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetDecisionClass, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { decisionId: entity.id };

    await getDecisionClass(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetDecisionClass.execute).toHaveBeenCalledWith(expect.objectContaining({ decisionId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { decisionId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetDecisionClass, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getDecisionClass(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
