/**
 * ExecuteSignLiabilityTerms - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSignLiabilityTerms Use Case
 *
 * DDD: Application use case for get Sign.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SignLiabilityTermsInput, SignLiabilityTermsOutput } from "../dto/sign.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alliora/services/_shared/index.js";
import type { SignRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteSignLiabilityTerms {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly sign: SignRepository
  ) {}

  async execute(input: SignLiabilityTermsInput): Promise<SignLiabilityTermsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.expId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).liabilityId) {
      throw new ValidationError("liabilityId is required");
    }
    const liabilityId = (input as any).liabilityId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.sign.signLiabilityTerms({ liabilityId: liabilityId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${liabilityId}`);
    }

    return entity as SignLiabilityTermsOutput;
  }
}
