/**
 * ExecuteListExperienceOwnershipMaps - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListExperienceOwnershipMaps Use Case
 *
 * DDD: Application use case for list ExperienceMap.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListExperienceOwnershipMapsInput, ListExperienceOwnershipMapsOutput } from "../dto/experience-map.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alliora/services/_shared/index.js";
import type { ExperienceMapRepository } from "../ports";

export class ExecuteListExperienceOwnershipMaps {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly experienceMap: ExperienceMapRepository
  ) {}

  async execute(input: ListExperienceOwnershipMapsInput): Promise<ListExperienceOwnershipMapsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.expId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.experienceMap.listExperienceOwnershipMaps({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListExperienceOwnershipMapsOutput;
  }
}
