/**
 * Handlers for Outcome
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: stagegates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { StagegatesDomainModule } from "../dependencies/stagegates-ddd.dependencies.js";
import type { DecideStageGateOutcomeInput } from "@alliora/services/stagegates";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/stage-gates/{gateId}/outcome
 * Operation: decideStageGateOutcome
 */
export async function decideStageGateOutcome(
  request: FastifyRequest<{ Params: { gateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: StagegatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    gateId: request.params.gateId,
    ...((request.body ?? {}) as object),
  };
  const result = await deps.useCases.outcomes.get.execute(input as any);
  return reply.code(200).send(result);
}


