/**
 * PartnershipContractRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PartnershipContractRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PartnershipContractRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PartnershipContractRepository,
} from "@alliora/services/decisions";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PartnershipContractRepositoryDdb } from "./partnership-contract-repository.ddb.js";

/**
 * PartnershipContractRepositoryAdapter
 *
 * Implements PartnershipContractRepository port for infrastructure layer.
 */
export class PartnershipContractRepositoryAdapter implements PartnershipContractRepository {
  private readonly ddb: PartnershipContractRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PartnershipContractRepositoryDdb(this.dynamoClient);
  }

  async listPartnershipContracts(input: Parameters<PartnershipContractRepository['listPartnershipContracts']>[0]): Promise<Awaited<ReturnType<PartnershipContractRepository['listPartnershipContracts']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listPartnershipContracts(input);
  }

  async createPartnershipContract(input: Parameters<PartnershipContractRepository['createPartnershipContract']>[0]): Promise<Awaited<ReturnType<PartnershipContractRepository['createPartnershipContract']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createPartnershipContract(input);
  }

  async updatePartnershipContract(input: Parameters<PartnershipContractRepository['updatePartnershipContract']>[0]): Promise<Awaited<ReturnType<PartnershipContractRepository['updatePartnershipContract']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updatePartnershipContract(input);
  }
}
