/**
 * ProfitPoolHypothesisRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProfitPoolHypothesisRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ProfitPoolHypothesisRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ProfitPoolHypothesisRepository,
} from "@alliora/services/decisions";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ProfitPoolHypothesisRepositoryDdb } from "./profit-pool-hypothesis-repository.ddb.js";

/**
 * ProfitPoolHypothesisRepositoryAdapter
 *
 * Implements ProfitPoolHypothesisRepository port for infrastructure layer.
 */
export class ProfitPoolHypothesisRepositoryAdapter implements ProfitPoolHypothesisRepository {
  private readonly ddb: ProfitPoolHypothesisRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ProfitPoolHypothesisRepositoryDdb(this.dynamoClient);
  }

  async listProfitPoolHypotheses(input: Parameters<ProfitPoolHypothesisRepository['listProfitPoolHypotheses']>[0]): Promise<Awaited<ReturnType<ProfitPoolHypothesisRepository['listProfitPoolHypotheses']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listProfitPoolHypotheses(input);
  }

  async createProfitPoolHypothesis(input: Parameters<ProfitPoolHypothesisRepository['createProfitPoolHypothesis']>[0]): Promise<Awaited<ReturnType<ProfitPoolHypothesisRepository['createProfitPoolHypothesis']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createProfitPoolHypothesis(input);
  }
}
