/**
 * Handlers for Capability
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capabilities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CapabilitiesDomainModule } from "../dependencies/capabilities-ddd.dependencies.js";
import type { CreateCapabilityInput, GetCapabilityInput, ListCapabilitiesInput, UpdateCapabilityInput } from "@alliora/services/capabilities";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/capabilities
 * Operation: listCapabilities
 */
export async function listCapabilities(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], force?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: CapabilitiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    ...((request.query ?? {}) as object),
  };
  const result = await deps.useCases.capabilities.list.execute(input as any);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/capabilities
 * Operation: createCapability
 */
export async function createCapability(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: CapabilitiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    ...((request.body ?? {}) as object),
  };
  const result = await deps.useCases.capabilities.create.execute(input as any);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/capabilities/{capabilityId}
 * Operation: getCapability
 */
export async function getCapability(
  request: FastifyRequest<{ Params: { capabilityId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: CapabilitiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    capabilityId: request.params.capabilityId,
  };
  const result = await deps.useCases.capabilities.get.execute(input as any);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/capabilities/{capabilityId}
 * Operation: updateCapability
 */
export async function updateCapability(
  request: FastifyRequest<{ Params: { capabilityId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: CapabilitiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    capabilityId: request.params.capabilityId,
    ...((request.body ?? {}) as object),
  };
  const result = await deps.useCases.capabilities.update.execute(input as any);
  return reply.code(200).send(result);
}


