/**
 * Dependency Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dependencies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/dependencies.openapi.types.js";
import { schemas } from "../schemas/dependencies.schemas.js";

/**
 * Entity: DependencyEntity
 * Description: Represents the Dependency domain model.
 * Source: schemas.SitDependency
 * Type: Persisted Entity (x-dynamodb)
 */
export const DependencyEntitySchema = schemas.SitDependency;
export type DependencyEntity = components["schemas"]["SitDependency"];
