/**
 * Handlers for CostCompare
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DecisionsDomainModule } from "../dependencies/decisions-ddd.dependencies.js";
import type { CreateCostCompareInput, ListCostComparesInput } from "@alliora/services/decisions";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/cost-compares
 * Operation: listCostCompares
 */
export async function listCostCompares(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], capabilityId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: DecisionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    ...((request.query ?? {}) as object),
  };
  const result = await deps.useCases.costCompares.list.execute(input as any);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/cost-compares
 * Operation: createCostCompare
 */
export async function createCostCompare(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: DecisionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    ...((request.body ?? {}) as object),
  };
  const result = await deps.useCases.costCompares.create.execute(input as any);
  return reply.code(201).send(result);
}


