/**
 * Handlers for Test
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DecisionsDomainModule } from "../dependencies/decisions-ddd.dependencies.js";
import type { AttachProfitPoolTestInput } from "@alliora/services/decisions";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/profit-pool-hypotheses/{hypothesisId}/test
 * Operation: attachProfitPoolTest
 */
export async function attachProfitPoolTest(
  request: FastifyRequest<{ Params: { hypothesisId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DecisionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    hypothesisId: request.params.hypothesisId,
    ...((request.body ?? {}) as object),
  };
  const result = await deps.useCases.tests.get.execute(input as any);
  return reply.code(200).send(result);
}


