/**
 * Routes for RegionalConstraint
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capabilities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createRegionalConstraint, listRegionalConstraints } from "../handlers/regional-constraint.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function regionalConstraintRoutes(fastify: FastifyInstance) {
  // POST /v1/regional-constraints (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/regional-constraints",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCapabilitiesDependenciesForRequest();
        await createRegionalConstraint(request, reply, deps);
      });
    }
  );


  // GET /v1/regional-constraints (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/regional-constraints",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCapabilitiesDependenciesForRequest();
        await listRegionalConstraints(request, reply, deps);
      });
    }
  );


}
