/**
 * Report Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/reports.openapi.types.js";
import { schemas } from "../schemas/reports.schemas.js";

/**
 * Entity: ReportEntity
 * Description: Represents the Report domain model.
 * Source: schemas.PortfolioReport
 * Type: Persisted Entity (x-dynamodb)
 */
export const ReportEntitySchema = schemas.PortfolioReport;
export type ReportEntity = components["schemas"]["PortfolioReport"];
