/**
 * Handlers for Sign
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ExperienceDomainModule } from "../dependencies/experience-ddd.dependencies.js";
import type { SignLiabilityTermsInput } from "@alliora/services/experience";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/liability-terms/{liabilityId}/sign
 * Operation: signLiabilityTerms
 */
export async function signLiabilityTerms(
  request: FastifyRequest<{ Params: { liabilityId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ExperienceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    liabilityId: request.params.liabilityId,
  };
  const result = await deps.useCases.signs.get.execute(input as any);
  return reply.code(200).send(result);
}


