/**
 * ListCapabilities handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capabilities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listCapabilities } from "@alliora/api-server/domains/capabilities/handlers";
import type { CapabilitiesDDDDependencies } from "@alliora/api-server/domains/capabilities";
import { createCapability as createCapabilityEntity } from "@alliora/factories/capabilities";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@alliora/tests/shared";
import { CAPABILITIES_USE_CASES } from "../__factories__/use-cases.js";

describe("ListCapabilities", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: CapabilitiesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<CapabilitiesDDDDependencies>(
      CAPABILITIES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createCapabilityEntity({ orgId }),
      createCapabilityEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListCapabilities, "execute").mockResolvedValue(useCaseResult);

    await listCapabilities(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListCapabilities.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
