/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildAlertsDomainModule } from "./alerts/dependencies/alerts-ddd.dependencies.js";
export { buildCapabilitiesDomainModule } from "./capabilities/dependencies/capabilities-ddd.dependencies.js";
export { buildDecisionsDomainModule } from "./decisions/dependencies/decisions-ddd.dependencies.js";
export { buildDependenciesDomainModule } from "./dependencies/dependencies/dependencies-ddd.dependencies.js";
export { buildExperienceDomainModule } from "./experience/dependencies/experience-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildReportsDomainModule } from "./reports/dependencies/reports-ddd.dependencies.js";
export { buildStagegatesDomainModule } from "./stagegates/dependencies/stagegates-ddd.dependencies.js";
export { buildWorkforceDomainModule } from "./workforce/dependencies/workforce-ddd.dependencies.js";

// Export all domain dependency types
export type { AlertsDomainModule } from "./alerts/dependencies/alerts-ddd.dependencies.js";
export type { CapabilitiesDomainModule } from "./capabilities/dependencies/capabilities-ddd.dependencies.js";
export type { DecisionsDomainModule } from "./decisions/dependencies/decisions-ddd.dependencies.js";
export type { DependenciesDomainModule } from "./dependencies/dependencies/dependencies-ddd.dependencies.js";
export type { ExperienceDomainModule } from "./experience/dependencies/experience-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { ReportsDomainModule } from "./reports/dependencies/reports-ddd.dependencies.js";
export type { StagegatesDomainModule } from "./stagegates/dependencies/stagegates-ddd.dependencies.js";
export type { WorkforceDomainModule } from "./workforce/dependencies/workforce-ddd.dependencies.js";
