/**
 * Handlers for Acknowledge
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AlertsDomainModule } from "../dependencies/alerts-ddd.dependencies.js";
import type { AcknowledgePlatformRiskAlertInput } from "@alliora/services/alerts";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/alerts/{alertId}/acknowledge
 * Operation: acknowledgePlatformRiskAlert
 */
export async function acknowledgePlatformRiskAlert(
  request: FastifyRequest<{ Params: { alertId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AlertsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    alertId: request.params.alertId,
  };
  const result = await deps.useCases.acknowledges.get.execute(input as any);
  return reply.code(200).send(result);
}


