/**
 * Handlers for Alert
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AlertsDomainModule } from "../dependencies/alerts-ddd.dependencies.js";
import type { GetPlatformRiskAlertInput, ListPlatformRiskAlertsInput, RaisePlatformRiskAlertInput } from "@alliora/services/alerts";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/alerts
 * Operation: listPlatformRiskAlerts
 */
export async function listPlatformRiskAlerts(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: AlertsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    ...((request.query ?? {}) as object),
  };
  const result = await deps.useCases.alerts.list.execute(input as any);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/alerts
 * Operation: raisePlatformRiskAlert
 */
export async function raisePlatformRiskAlert(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: AlertsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    ...((request.body ?? {}) as object),
  };
  const result = await deps.useCases.alerts.raise.execute(input as any);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/alerts/{alertId}
 * Operation: getPlatformRiskAlert
 */
export async function getPlatformRiskAlert(
  request: FastifyRequest<{ Params: { alertId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AlertsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    alertId: request.params.alertId,
  };
  const result = await deps.useCases.alerts.get.execute(input as any);
  return reply.code(200).send(result);
}


