/**
 * Routes for ProfitPoolHypothesis
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createProfitPoolHypothesis, listProfitPoolHypotheses } from "../handlers/profit-pool-hypothesis.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function profitPoolHypothesisRoutes(fastify: FastifyInstance) {
  // POST /v1/profit-pool-hypotheses (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/profit-pool-hypotheses",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDecisionsDependenciesForRequest();
        await createProfitPoolHypothesis(request, reply, deps);
      });
    }
  );


  // GET /v1/profit-pool-hypotheses (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/profit-pool-hypotheses",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDecisionsDependenciesForRequest();
        await listProfitPoolHypotheses(request, reply, deps);
      });
    }
  );


}
