/**
 * Routes for Test
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { attachProfitPoolTest } from "../handlers/test.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function testRoutes(fastify: FastifyInstance) {
  // POST /v1/profit-pool-hypotheses/{hypothesisId}/test (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/profit-pool-hypotheses/:hypothesisId/test",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { hypothesisId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDecisionsDependenciesForRequest();
        await attachProfitPoolTest(request, reply, deps);
      });
    }
  );


}
