/**
 * Repository interface for Liability
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  LiabilityEntity
} from "../models/liability.entity.js";
import type {
  ExperienceOwnershipMap
} from "../types/index.js";
/**
 * LiabilityRepository Interface
 */
export interface LiabilityRepository extends CreateReadRepository<LiabilityEntity, ExperienceOwnershipMap, string, Record<string, never>> {

}
