/**
 * ExecuteGetSitSpendBlock - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dependencies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetSitSpendBlock Use Case
 *
 * DDD: Application use case for get SpendBlock.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetSitSpendBlockInput, GetSitSpendBlockOutput } from "../dto/spend-block.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alliora/services/_shared/index.js";
import type { SpendBlockRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetSitSpendBlock {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly spendBlock: SpendBlockRepository
  ) {}

  async execute(input: GetSitSpendBlockInput): Promise<GetSitSpendBlockOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.sitId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).dependencyId) {
      throw new ValidationError("dependencyId is required");
    }
    const dependencyId = (input as any).dependencyId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.spendBlock.getSitSpendBlock({ dependencyId: dependencyId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${dependencyId}`);
    }

    return entity as GetSitSpendBlockOutput;
  }
}
