/**
 * ExecuteUpdateSitDependency - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dependencies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateSitDependency Use Case
 *
 * DDD: Application use case for update Dependency.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateSitDependencyInput, UpdateSitDependencyOutput } from "../dto/dependency.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alliora/services/_shared/index.js";
import type { DependencyRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateSitDependency {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dependency: DependencyRepository
  ) {}

  async execute(input: UpdateSitDependencyInput): Promise<UpdateSitDependencyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.sitId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).dependencyId) {
      throw new ValidationError("dependencyId is required");
    }
    const dependencyId = (input as any).dependencyId;
    // No get/list operation for this resource - call update directly
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.dependency.updateSitDependency({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateSitDependencyOutput;
  }
}
