/**
 * CreateSign DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { SignLiabilityTermsParams } from "@alliora/core/experience";

export function createCreateSignRequest(overrides: Partial<SignLiabilityTermsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
