/**
 * Publish Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { PublishEntity } from "@alliora/core/reports/models/index.js";
import { reportsSchemas } from "@alliora/core/reports";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "rpt";

export function createPublish(overrides: Partial<PublishEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    capabilityCount: overrides.capabilityCount ?? faker.number.int({ min: 1, max: 100 }),
    killRate: overrides.killRate ?? faker.number.int(),
    period: overrides.period ?? faker.lorem.word(),
    reportId: overrides.reportId ?? `rpt_${ulid().toLowerCase()}`,
    sitConcentrationIndex: overrides.sitConcentrationIndex ?? faker.number.int(),
    status: overrides.status ?? "draft",
    ...overrides,
  };

  return reportsSchemas.PortfolioReport.parse(raw);
}

export function publishBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createPublish(overrides));
}
