/**
 * CreateAcknowledge DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { AcknowledgePlatformRiskAlertParams } from "@alliora/core/alerts";

export function createCreateAcknowledgeRequest(overrides: Partial<AcknowledgePlatformRiskAlertParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
