/**
 * Routes for StageGate
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: stagegates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createStageGate, getStageGate, listStageGates } from "../handlers/stage-gate.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function stageGateRoutes(fastify: FastifyInstance) {
  // POST /v1/stage-gates (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/stage-gates",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getStagegatesDependenciesForRequest();
        await createStageGate(request, reply, deps);
      });
    }
  );


  // GET /v1/stage-gates (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/stage-gates",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getStagegatesDependenciesForRequest();
        await listStageGates(request, reply, deps);
      });
    }
  );


  // GET /v1/stage-gates/{gateId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/stage-gates/:gateId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { gateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getStagegatesDependenciesForRequest();
        await getStageGate(request, reply, deps);
      });
    }
  );


}
