/**
 * ListExperienceMap DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListExperienceOwnershipMapsParams } from "@alliora/core/experience";

export function createListExperienceMapRequest(overrides: Partial<ListExperienceOwnershipMapsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
