/**
 * Handlers for Dependency
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dependencies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DependenciesDomainModule } from "../dependencies/dependencies-ddd.dependencies.js";
import type { GetSitDependencyInput, ListSitDependenciesInput, RegisterSitDependencyInput, UpdateSitDependencyInput } from "@alliora/services/dependencies";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/dependencies
 * Operation: listSitDependencies
 */
export async function listSitDependencies(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: DependenciesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    ...((request.query ?? {}) as object),
  };
  const result = await deps.useCases.dependencies.list.execute(input as any);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/dependencies
 * Operation: registerSitDependency
 */
export async function registerSitDependency(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: DependenciesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    ...((request.body ?? {}) as object),
  };
  const result = await deps.useCases.dependencies.create.execute(input as any);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/dependencies/{dependencyId}
 * Operation: getSitDependency
 */
export async function getSitDependency(
  request: FastifyRequest<{ Params: { dependencyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DependenciesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    dependencyId: request.params.dependencyId,
  };
  const result = await deps.useCases.dependencies.get.execute(input as any);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/dependencies/{dependencyId}
 * Operation: updateSitDependency
 */
export async function updateSitDependency(
  request: FastifyRequest<{ Params: { dependencyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DependenciesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    dependencyId: request.params.dependencyId,
    ...((request.body ?? {}) as object),
  };
  const result = await deps.useCases.dependencies.update.execute(input as any);
  return reply.code(200).send(result);
}


