/**
 * Handlers for SitException
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dependencies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DependenciesDomainModule } from "../dependencies/dependencies-ddd.dependencies.js";
import type { ListSitLimitExceptionsInput, RequestSitLimitExceptionInput } from "@alliora/services/dependencies";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/sit-exceptions
 * Operation: listSitLimitExceptions
 */
export async function listSitLimitExceptions(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: DependenciesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    ...((request.query ?? {}) as object),
  };
  const result = await deps.useCases.sitExceptions.list.execute(input as any);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/sit-exceptions
 * Operation: requestSitLimitException
 */
export async function requestSitLimitException(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: DependenciesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    ...((request.body ?? {}) as object),
  };
  const result = await deps.useCases.sitExceptions.get.execute(input as any);
  return reply.code(201).send(result);
}


