/**
 * Stagegates DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: stagegates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Stagegates Domain Module - Composition root
 *
 * DDD: Composition root for stagegates domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  EvidenceRepositoryAdapter,
  OutcomeRepositoryAdapter,
  StageGateRepositoryAdapter,
} from "@alliora/adapters/stagegates";
import { getIdGeneratorService } from "@alliora/adapters";
import type { AdapterDynamoDBClient } from "@alliora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateStageGate,
  ExecuteDecideStageGateOutcome,
  ExecuteGetEvidencePack,
  ExecuteGetStageGate,
  ExecuteListStageGates,
  ExecuteSubmitEvidencePack,
} from "@alliora/services/stagegates/usecases";
// Ports (interfaces)
import type {
  EvidenceRepository,
  OutcomeRepository,
  StageGateRepository,
} from "@alliora/services/stagegates/ports";

export interface StagegatesDomainModule {
  repos: {
    evidences: EvidenceRepository;
    outcomes: OutcomeRepository;
    stageGates: StageGateRepository;
  };
  useCases: {
    evidences: {
      create: ExecuteSubmitEvidencePack;
      get: ExecuteGetEvidencePack;
    };
    outcomes: {
      get: ExecuteDecideStageGateOutcome;
    };
    stageGates: {
      create: ExecuteCreateStageGate;
      get: ExecuteGetStageGate;
      list: ExecuteListStageGates;
    };
  };
}

export function buildStagegatesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): StagegatesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      evidences?: EvidenceRepository;
      outcomes?: OutcomeRepository;
      stageGates?: StageGateRepository;
    } = {};

    obj.evidences = new EvidenceRepositoryAdapter(dynamoClient);
    obj.outcomes = new OutcomeRepositoryAdapter(dynamoClient);
    obj.stageGates = new StageGateRepositoryAdapter(dynamoClient);
    return {
      evidences: obj.evidences!,
      outcomes: obj.outcomes!,
      stageGates: obj.stageGates!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    evidences: {
      create: new ExecuteSubmitEvidencePack(executionContext, idGenerator, repos.evidences),
      get: new ExecuteGetEvidencePack(executionContext, idGenerator, repos.evidences),
    },
    outcomes: {
      get: new ExecuteDecideStageGateOutcome(executionContext, idGenerator, repos.outcomes),
    },
    stageGates: {
      create: new ExecuteCreateStageGate(executionContext, idGenerator, repos.stageGates),
      get: new ExecuteGetStageGate(executionContext, idGenerator, repos.stageGates),
      list: new ExecuteListStageGates(executionContext, idGenerator, repos.stageGates),
    },
  };
  return { repos, useCases: useCases as StagegatesDomainModule["useCases"] };
}
