/**
 * Sign Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { SignEntity } from "@alliora/core/experience/models/index.js";
import { experienceSchemas } from "@alliora/core/experience";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "exp";

export function createSign(overrides: Partial<SignEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    distributorLiability: overrides.distributorLiability ?? faker.lorem.word(),
    liabilityId: overrides.liabilityId ?? `lia_${ulid().toLowerCase()}`,
    manufacturerLiability: overrides.manufacturerLiability ?? faker.lorem.word(),
    mapId: overrides.mapId ?? `exp_${ulid().toLowerCase()}`,
    signed: overrides.signed ?? faker.datatype.boolean(),
    ...overrides,
  };

  return experienceSchemas.LiabilityTerms.parse(raw);
}

export function signBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createSign(overrides));
}
