/**
 * GetDecision DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetDecisionClassParams } from "@alliora/core/decisions";

export function createGetDecisionRequest(overrides: Partial<GetDecisionClassParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
