/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: workforce
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./hr-signoff-repository.ddb.js";
export * from "./workforce-map-repository.ddb.js";
export * from "./hr-signoff-repository.adapter.js";
export * from "./workforce-map-repository.adapter.js";
