/**
 * WorkforceMapRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: workforce
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * WorkforceMapRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements WorkforceMapRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  WorkforceMapRepository,
} from "@alliora/services/workforce";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { WorkforceMapRepositoryDdb } from "./workforce-map-repository.ddb.js";

/**
 * WorkforceMapRepositoryAdapter
 *
 * Implements WorkforceMapRepository port for infrastructure layer.
 */
export class WorkforceMapRepositoryAdapter implements WorkforceMapRepository {
  private readonly ddb: WorkforceMapRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new WorkforceMapRepositoryDdb(this.dynamoClient);
  }

  async listBionicRoleMaps(input: Parameters<WorkforceMapRepository['listBionicRoleMaps']>[0]): Promise<Awaited<ReturnType<WorkforceMapRepository['listBionicRoleMaps']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listBionicRoleMaps(input);
  }

  async createBionicRoleMap(input: Parameters<WorkforceMapRepository['createBionicRoleMap']>[0]): Promise<Awaited<ReturnType<WorkforceMapRepository['createBionicRoleMap']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createBionicRoleMap(input);
  }

  async getBionicRoleMap(input: Parameters<WorkforceMapRepository['getBionicRoleMap']>[0]): Promise<Awaited<ReturnType<WorkforceMapRepository['getBionicRoleMap']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getBionicRoleMap(input);
  }
}
