/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capabilities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Capabilities Domain Use Cases
 * 
 * List of all use case names for the capabilities domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const CAPABILITIES_USE_CASES = [
  "executeCreateCapability",
  "executeCreateRegionalConstraint",
  "executeGetCapability",
  "executeListCapabilities",
  "executeListRegionalConstraints",
  "executeTagCapabilityForces",
  "executeUpdateCapability"
] as const;
