/**
 * StageGateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: stagegates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * StageGateRepository Port
 *
 * DDD: Application port for stagegaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateStageGateInput, CreateStageGateOutput, GetStageGateInput, GetStageGateOutput, ListStageGatesInput, ListStageGatesOutput } from "../dto/stage-gate.dto";
export interface StageGateRepository {
  listStageGates(input: ListStageGatesInput): Promise<ListStageGatesOutput>;
  createStageGate(input: CreateStageGateInput): Promise<CreateStageGateOutput>;
  getStageGate(input: GetStageGateInput): Promise<GetStageGateOutput>;
}

export type { CreateStageGateInput, CreateStageGateOutput, GetStageGateInput, GetStageGateOutput, ListStageGatesInput, ListStageGatesOutput } from "../dto/stage-gate.dto";
