/**
 * WorkforceMap Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: workforce
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/workforce.openapi.types.js";
import { schemas } from "../schemas/workforce.schemas.js";

/**
 * Entity: WorkforceMapEntity
 * Description: Represents the WorkforceMap domain model.
 * Source: schemas.BionicRoleMap
 * Type: Persisted Entity (x-dynamodb)
 */
export const WorkforceMapEntitySchema = schemas.BionicRoleMap;
export type WorkforceMapEntity = components["schemas"]["BionicRoleMap"];
