/**
 * UpdatePartnershipContract handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { updatePartnershipContract } from "@alliora/api-server/domains/decisions/handlers";
import type { DecisionsDDDDependencies } from "@alliora/api-server/domains/decisions";
import { createPartnershipContract as createPartnershipContractEntity } from "@alliora/factories/decisions";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@alliora/tests/shared";
import { DECISIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("UpdatePartnershipContract", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DecisionsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DecisionsDDDDependencies>(
      DECISIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = createPartnershipContractEntity({ orgId });
    const input = {} as any;
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { contractId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeUpdatePartnershipContract, "execute").mockResolvedValue(useCaseResult);

    await updatePartnershipContract(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeUpdatePartnershipContract.execute).toHaveBeenCalledWith(expect.objectContaining({ contractId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
