/**
 * ListPortfolioReports handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listPortfolioReports } from "@alliora/api-server/domains/reports/handlers";
import type { ReportsDDDDependencies } from "@alliora/api-server/domains/reports";
import { createReport as createReportEntity } from "@alliora/factories/reports";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@alliora/tests/shared";
import { REPORTS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListPortfolioReports", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ReportsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ReportsDDDDependencies>(
      REPORTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createReportEntity({ orgId }),
      createReportEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListPortfolioReports, "execute").mockResolvedValue(useCaseResult);

    await listPortfolioReports(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListPortfolioReports.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
