/**
 * SitExceptionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dependencies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SitExceptionRepository Port
 *
 * DDD: Application port for sitexceptionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListSitLimitExceptionsInput, ListSitLimitExceptionsOutput, RequestSitLimitExceptionInput, RequestSitLimitExceptionOutput } from "../dto/sit-exception.dto";
export interface SitExceptionRepository {
  listSitLimitExceptions(input: ListSitLimitExceptionsInput): Promise<ListSitLimitExceptionsOutput>;
  requestSitLimitException(input: RequestSitLimitExceptionInput): Promise<RequestSitLimitExceptionOutput>;
}

export type { ListSitLimitExceptionsInput, ListSitLimitExceptionsOutput, RequestSitLimitExceptionInput, RequestSitLimitExceptionOutput } from "../dto/sit-exception.dto";
