/**
 * SpendBlockRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dependencies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SpendBlockRepository Port
 *
 * DDD: Application port for spendblockrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetSitSpendBlockInput, GetSitSpendBlockOutput } from "../dto/spend-block.dto";
export interface SpendBlockRepository {
  getSitSpendBlock(input: GetSitSpendBlockInput): Promise<GetSitSpendBlockOutput>;
}

export type { GetSitSpendBlockInput, GetSitSpendBlockOutput } from "../dto/spend-block.dto";
