/**
 * CreateBionicRoleMap handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: workforce
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createBionicRoleMap } from "@alliora/api-server/domains/workforce/handlers";
import type { WorkforceDDDDependencies } from "@alliora/api-server/domains/workforce";
import { createWorkforceMap as createWorkforceMapEntity } from "@alliora/factories/workforce";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@alliora/tests/shared";
import { WORKFORCE_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateBionicRoleMap", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: WorkforceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<WorkforceDDDDependencies>(
      WORKFORCE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createWorkforceMapEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateBionicRoleMap, "execute").mockResolvedValue(useCaseResult);

    await createBionicRoleMap(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateBionicRoleMap.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
