/**
 * ListBionicRoleMaps handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: workforce
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listBionicRoleMaps } from "@alliora/api-server/domains/workforce/handlers";
import type { WorkforceDDDDependencies } from "@alliora/api-server/domains/workforce";
import { createWorkforceMap as createWorkforceMapEntity } from "@alliora/factories/workforce";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@alliora/tests/shared";
import { WORKFORCE_USE_CASES } from "../__factories__/use-cases.js";

describe("ListBionicRoleMaps", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: WorkforceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<WorkforceDDDDependencies>(
      WORKFORCE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createWorkforceMapEntity({ orgId }),
      createWorkforceMapEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListBionicRoleMaps, "execute").mockResolvedValue(useCaseResult);

    await listBionicRoleMaps(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListBionicRoleMaps.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
