/**
 * Dependencies DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dependencies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Dependencies Domain Module - Composition root
 *
 * DDD: Composition root for dependencies domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DependencyRepositoryAdapter,
  SitExceptionRepositoryAdapter,
  SpendBlockRepositoryAdapter,
} from "@alliora/adapters/dependencies";
import { getIdGeneratorService } from "@alliora/adapters";
import type { AdapterDynamoDBClient } from "@alliora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetSitDependency,
  ExecuteGetSitSpendBlock,
  ExecuteListSitDependencies,
  ExecuteListSitLimitExceptions,
  ExecuteRegisterSitDependency,
  ExecuteRequestSitLimitException,
  ExecuteUpdateSitDependency,
} from "@alliora/services/dependencies/usecases";
// Ports (interfaces)
import type {
  DependencyRepository,
  SitExceptionRepository,
  SpendBlockRepository,
} from "@alliora/services/dependencies/ports";

export interface DependenciesDomainModule {
  repos: {
    dependencies: DependencyRepository;
    sitExceptions: SitExceptionRepository;
    spendBlocks: SpendBlockRepository;
  };
  useCases: {
    dependencies: {
      create: ExecuteRegisterSitDependency;
      get: ExecuteGetSitDependency;
      list: ExecuteListSitDependencies;
      update: ExecuteUpdateSitDependency;
    };
    sitExceptions: {
      get: ExecuteRequestSitLimitException;
      list: ExecuteListSitLimitExceptions;
    };
    spendBlocks: {
      get: ExecuteGetSitSpendBlock;
    };
  };
}

export function buildDependenciesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): DependenciesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      dependencies?: DependencyRepository;
      sitExceptions?: SitExceptionRepository;
      spendBlocks?: SpendBlockRepository;
    } = {};

    obj.dependencies = new DependencyRepositoryAdapter(dynamoClient);
    obj.sitExceptions = new SitExceptionRepositoryAdapter(dynamoClient);
    obj.spendBlocks = new SpendBlockRepositoryAdapter(dynamoClient);
    return {
      dependencies: obj.dependencies!,
      sitExceptions: obj.sitExceptions!,
      spendBlocks: obj.spendBlocks!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    dependencies: {
      create: new ExecuteRegisterSitDependency(executionContext, idGenerator, repos.dependencies),
      get: new ExecuteGetSitDependency(executionContext, idGenerator, repos.dependencies),
      list: new ExecuteListSitDependencies(executionContext, idGenerator, repos.dependencies),
      update: new ExecuteUpdateSitDependency(executionContext, idGenerator, repos.dependencies),
    },
    sitExceptions: {
      get: new ExecuteRequestSitLimitException(executionContext, idGenerator, repos.sitExceptions),
      list: new ExecuteListSitLimitExceptions(executionContext, idGenerator, repos.sitExceptions),
    },
    spendBlocks: {
      get: new ExecuteGetSitSpendBlock(executionContext, idGenerator, repos.spendBlocks),
    },
  };
  return { repos, useCases: useCases as DependenciesDomainModule["useCases"] };
}
