/**
 * Repository interface for CostCompare
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  CostCompareEntity
} from "../models/cost-compare.entity.js";
import type {
  ListCostComparesParams,
  CostCompare
} from "../types/index.js";
/**
 * CostCompareRepository Interface
 */
export interface CostCompareRepository extends CreateReadRepository<CostCompareEntity, CostCompare, string, ListCostComparesParams> {

}
