/**
 * Sign Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/experience.openapi.types.js";
import { schemas } from "../schemas/experience.schemas.js";

/**
 * Entity: SignEntity
 * Description: Represents the Sign domain model.
 * Source: schemas.LiabilityTerms
 * Type: Persisted Entity (x-dynamodb)
 */
export const SignEntitySchema = schemas.LiabilityTerms;
export type SignEntity = components["schemas"]["LiabilityTerms"];
