/**
 * Repository interface for ForceTag
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: capabilities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ForceTagEntity
} from "../models/force-tag.entity.js";
import type {
  Capability
} from "../types/index.js";
/**
 * ForceTagRepository Interface
 */
export interface ForceTagRepository extends CreateReadRepository<ForceTagEntity, Capability, string, Record<string, never>> {

}
