/**
 * Repository interface for WorkforceMap
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: workforce
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  WorkforceMapEntity
} from "../models/workforce-map.entity.js";
import type {
  ListBionicRoleMapsParams,
  BionicRoleMap
} from "../types/index.js";
/**
 * WorkforceMapRepository Interface
 */
export interface WorkforceMapRepository extends CreateReadRepository<WorkforceMapEntity, BionicRoleMap, string, ListBionicRoleMapsParams> {

}
