/**
 * ExperienceMapRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExperienceMapRepository Port
 *
 * DDD: Application port for experiencemaprepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateExperienceOwnershipMapInput, CreateExperienceOwnershipMapOutput, GetExperienceOwnershipMapInput, GetExperienceOwnershipMapOutput, ListExperienceOwnershipMapsInput, ListExperienceOwnershipMapsOutput } from "../dto/experience-map.dto";
export interface ExperienceMapRepository {
  listExperienceOwnershipMaps(input: ListExperienceOwnershipMapsInput): Promise<ListExperienceOwnershipMapsOutput>;
  createExperienceOwnershipMap(input: CreateExperienceOwnershipMapInput): Promise<CreateExperienceOwnershipMapOutput>;
  getExperienceOwnershipMap(input: GetExperienceOwnershipMapInput): Promise<GetExperienceOwnershipMapOutput>;
}

export type { CreateExperienceOwnershipMapInput, CreateExperienceOwnershipMapOutput, GetExperienceOwnershipMapInput, GetExperienceOwnershipMapOutput, ListExperienceOwnershipMapsInput, ListExperienceOwnershipMapsOutput } from "../dto/experience-map.dto";
