/**
 * LiabilityRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LiabilityRepository Port
 *
 * DDD: Application port for liabilityrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AttachLiabilityTermsInput, AttachLiabilityTermsOutput } from "../dto/liability.dto";
export interface LiabilityRepository {
  attachLiabilityTerms(input: AttachLiabilityTermsInput): Promise<AttachLiabilityTermsOutput>;
}

export type { AttachLiabilityTermsInput, AttachLiabilityTermsOutput } from "../dto/liability.dto";
