/**
 * PartnershipContract DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PartnershipContract DTOs
 *
 * DDD: Application DTOs for PartnershipContract use cases.
 */

import type { CreatePartnershipContractRequestInput, ListPartnershipContractsParams, UpdatePartnershipContractParams, UpdatePartnershipContractRequestInput } from "@alliora/core/decisions/types";

export type ListPartnershipContractsInput = ListPartnershipContractsParams;

export type CreatePartnershipContractInput = CreatePartnershipContractRequestInput;

export type UpdatePartnershipContractInput = UpdatePartnershipContractParams & UpdatePartnershipContractRequestInput;

export type ListPartnershipContractsOutput = {};

export type CreatePartnershipContractOutput = {};

export type UpdatePartnershipContractOutput = {};
