/**
 * AlertRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AlertRepository Port
 *
 * DDD: Application port for alertrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetPlatformRiskAlertInput, GetPlatformRiskAlertOutput, ListPlatformRiskAlertsInput, ListPlatformRiskAlertsOutput, RaisePlatformRiskAlertInput, RaisePlatformRiskAlertOutput } from "../dto/alert.dto";
export interface AlertRepository {
  listPlatformRiskAlerts(input: ListPlatformRiskAlertsInput): Promise<ListPlatformRiskAlertsOutput>;
  raisePlatformRiskAlert(input: RaisePlatformRiskAlertInput): Promise<RaisePlatformRiskAlertOutput>;
  getPlatformRiskAlert(input: GetPlatformRiskAlertInput): Promise<GetPlatformRiskAlertOutput>;
}

export type { GetPlatformRiskAlertInput, GetPlatformRiskAlertOutput, ListPlatformRiskAlertsInput, ListPlatformRiskAlertsOutput, RaisePlatformRiskAlertInput, RaisePlatformRiskAlertOutput } from "../dto/alert.dto";
