/**
 * ForceTag Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capabilities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/capabilities.openapi.types.js";
import { schemas } from "../schemas/capabilities.schemas.js";

/**
 * Entity: ForceTagEntity
 * Description: Represents the ForceTag domain model.
 * Source: schemas.Capability
 * Type: Persisted Entity (x-dynamodb)
 */
export const ForceTagEntitySchema = schemas.Capability;
export type ForceTagEntity = components["schemas"]["Capability"];
