/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dependencies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Dependencies Domain Use Cases
 * 
 * List of all use case names for the dependencies domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const DEPENDENCIES_USE_CASES = [
  "executeGetSitDependency",
  "executeGetSitSpendBlock",
  "executeListSitDependencies",
  "executeListSitLimitExceptions",
  "executeRegisterSitDependency",
  "executeRequestSitLimitException",
  "executeUpdateSitDependency"
] as const;
