/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the reports domain.
 * Use these factories in tests to create test data.
 */

export { createCreatePublishRequest } from "./publish/dto/create-publish.dto.factory.js";
export { createPortfolio } from "./portfolio/entity/portfolio.entity.factory.js";
export { createPublish } from "./publish/entity/publish.entity.factory.js";
export { createReport } from "./report/entity/report.entity.factory.js";
