/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Reports Domain Use Cases
 * 
 * List of all use case names for the reports domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const REPORTS_USE_CASES = [
  "executeGeneratePortfolioReport",
  "executeGetPortfolioReport",
  "executeListPortfolioReports",
  "executePublishPortfolioReport"
] as const;
