/**
 * Routes for Dependency
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dependencies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getSitDependency, listSitDependencies, registerSitDependency, updateSitDependency } from "../handlers/dependency.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function dependencyRoutes(fastify: FastifyInstance) {
  // GET /v1/dependencies (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/dependencies",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDependenciesDependenciesForRequest();
        await listSitDependencies(request, reply, deps);
      });
    }
  );


  // POST /v1/dependencies (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/dependencies",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDependenciesDependenciesForRequest();
        await registerSitDependency(request, reply, deps);
      });
    }
  );


  // GET /v1/dependencies/{dependencyId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/dependencies/:dependencyId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { dependencyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDependenciesDependenciesForRequest();
        await getSitDependency(request, reply, deps);
      });
    }
  );


  // PATCH /v1/dependencies/{dependencyId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/dependencies/:dependencyId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { dependencyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDependenciesDependenciesForRequest();
        await updateSitDependency(request, reply, deps);
      });
    }
  );


}
