/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dependencies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { sitExceptionRoutes } from "./sit-exception.routes.js";
export { dependencyRoutes } from "./dependency.routes.js";
export { spendBlockRoutes } from "./spend-block.routes.js";
