/**
 * Routes for SpendBlock
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dependencies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getSitSpendBlock } from "../handlers/spend-block.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function spendBlockRoutes(fastify: FastifyInstance) {
  // GET /v1/dependencies/{dependencyId}/spend-block (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/dependencies/:dependencyId/spend-block",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { dependencyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDependenciesDependenciesForRequest();
        await getSitSpendBlock(request, reply, deps);
      });
    }
  );


}
