/**
 * PublishPublisherAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PublishPublisherAdapter
 *
 * DDD: Infrastructure adapter that implements PublishPublisher port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PublishPublisher,
} from "@alliora/services/reports";
import { ProductSandbox } from "../_shared/product-sandbox.js";

export class PublishPublisherAdapter implements PublishPublisher {
  constructor(_http?: unknown) {}

  async publishPortfolioReport(input: Parameters<PublishPublisher['publishPortfolioReport']>[0]): Promise<Awaited<ReturnType<PublishPublisher['publishPortfolioReport']>>> {
    return ProductSandbox.publishPortfolioReport((input ?? {}) as Record<string, unknown>) as Awaited<
      ReturnType<PublishPublisher['publishPortfolioReport']>
    >;
  }
}
