/**
 * Routes for Sign
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { signLiabilityTerms } from "../handlers/sign.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function signRoutes(fastify: FastifyInstance) {
  // POST /v1/liability-terms/{liabilityId}/sign (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/liability-terms/:liabilityId/sign",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { liabilityId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getExperienceDependenciesForRequest();
        await signLiabilityTerms(request, reply, deps);
      });
    }
  );


}
