/**
 * ListSitException DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dependencies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListSitLimitExceptionsParams } from "@alliora/core/dependencies";

export function createListSitExceptionRequest(overrides: Partial<ListSitLimitExceptionsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
