/**
 * Acknowledge DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Acknowledge DTOs
 *
 * DDD: Application DTOs for Acknowledge use cases.
 */

import type { AcknowledgePlatformRiskAlertParams } from "@alliora/core/alerts/types";

export type AcknowledgePlatformRiskAlertInput = AcknowledgePlatformRiskAlertParams;

export type AcknowledgePlatformRiskAlertOutput = {};
