/**
 * Alert DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Alert DTOs
 *
 * DDD: Application DTOs for Alert use cases.
 */

import type { GetPlatformRiskAlertParams, ListPlatformRiskAlertsParams, RaisePlatformRiskAlertRequestInput } from "@alliora/core/alerts/types";

export type ListPlatformRiskAlertsInput = ListPlatformRiskAlertsParams;

export type RaisePlatformRiskAlertInput = RaisePlatformRiskAlertRequestInput;

export type GetPlatformRiskAlertInput = GetPlatformRiskAlertParams;

export type ListPlatformRiskAlertsOutput = {};

export type RaisePlatformRiskAlertOutput = {};

export type GetPlatformRiskAlertOutput = {};
